name: solo-rush-prod
services:
    db:
        image: dodeun/sr-database:v1
        container_name: SR-Database
        restart: unless-stopped
        env_file:
            - server/.env.prod
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - api-db

    api:
        depends_on:
            - db
        image: dodeun/sr-backend:v1.1
        container_name: SR-Backend
        restart: unless-stopped
        ports:
            - 3000:3000
        env_file:
            - server/.env.prod
        environment:
            - NODE_ENV=production
        networks:
            - api-db

    web:
        image: dodeun/sr-frontend:v1.2
        container_name: SR-Frontend
        restart: unless-stopped
        ports:
            - 80:80

volumes:
    mysql_data:
networks:
    api-db:
