services:
    db:
        image: mysql:8.0.42
        container_name: SR-Database
        restart: unless-stopped
        env_file:
            - server/.env
        volumes:
            - mysql_data:/var/lib/mysql
            - ./server/src/database/schema.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - api-db

    api:
        depends_on:
            - db
        build: ./server
        container_name: SR-Backend
        restart: unless-stopped
        ports:
            - 3000:3000
        env_file:
            - server/.env
        volumes:
            - /app/node_modules
        develop:
            watch:
                - path: ./server/package.json
                  action: rebuild
                - path: ./server/package-lock.json
                  action: rebuild
                - path: ./server
                  target: /app
                  action: sync
        networks:
            - api-db
            - web-api

    web:
        build: ./client
        container_name: SR-Frontend
        restart: unless-stopped
        ports:
            - 5173:5173
        env_file:
            - client/.env
        volumes:
            - /app/node_modules
        develop:
            watch:
                - path: ./client/package.json
                  action: rebuild
                - path: ./client/package-lock.json
                  action: rebuild
                - path: ./client/src
                  target: /app
                  action: sync
        networks:
            - web-api

volumes:
    mysql_data:
networks:
    api-db:
    web-api:
