INSERT INTO exemple (message) VALUES
('I told my computer I needed a break, and now it won’t stop sending me Kit-Kat ads.'),
('Why don’t scientists trust atoms? Because they make up everything!'),
('I’m on a seafood diet. I see food and I eat it.'),
('Parallel lines have so much in common. It’s a shame they’ll never meet.'),
('I would tell you a joke about construction, but I’m still working on it.'),
('Why did the scarecrow win an award? Because he was outstanding in his field!'),
('I’m reading a book on anti-gravity. It’s impossible to put down!'),
('Why don’t programmers like nature? Too many bugs.'),
('I asked the librarian if the library had books on paranoia. “They’re right behind you.”'),
('I told a joke about a roof once. It went over everyone’s head.'),
('Why did the coffee file a police report? It got mugged.'),
('I’m friends with all electricians. We have a current connection.'),
('I tried to catch fog yesterday. Mist.'),
('Why don’t eggs tell jokes? They’d crack each other up.'),
('I’m on a whiskey diet. I’ve lost three days already.'),
('If we shouldn’t eat at night, why is there a light in the fridge?'),
('I told my wife she was drawing her eyebrows too high. She looked surprised.'),
('What do you call fake spaghetti? An impasta.'),
('I’m so good at sleeping I can do it with my eyes closed.'),
('Why did the math book look sad? Because it had too many problems.');
