name: CI
on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev
jobs:
    test:
        name: API tests
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: install node
              uses: action/setup-node@v4
              with:
                  node-version: node
            - name: install API dependencies
              run: |
                  cd server
                  npm i
            - name: launch jest tests
              run: |
                  cd server
                  npm run test
